// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	MsgLogin
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgTypeCmd int32

const (
	MsgTypeCmd_UNSPECIFIED MsgTypeCmd = 0
	MsgTypeCmd_Login       MsgTypeCmd = 1
)

var MsgTypeCmd_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "Login",
}
var MsgTypeCmd_value = map[string]int32{
	"UNSPECIFIED": 0,
	"Login":       1,
}

func (x MsgTypeCmd) String() string {
	return proto1.EnumName(MsgTypeCmd_name, int32(x))
}
func (MsgTypeCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LoginMode int32

const (
	LoginMode_Default LoginMode = 0
)

var LoginMode_name = map[int32]string{
	0: "Default",
}
var LoginMode_value = map[string]int32{
	"Default": 0,
}

func (x LoginMode) String() string {
	return proto1.EnumName(LoginMode_name, int32(x))
}
func (LoginMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type MsgLogin struct {
	Account  string    `protobuf:"bytes,1,opt,name=account" json:"account,omitempty"`
	Password string    `protobuf:"bytes,2,opt,name=password" json:"password,omitempty"`
	Mode     LoginMode `protobuf:"varint,3,opt,name=mode,enum=proto.LoginMode" json:"mode,omitempty"`
	Userdata []byte    `protobuf:"bytes,4,opt,name=userdata,proto3" json:"userdata,omitempty"`
}

func (m *MsgLogin) Reset()                    { *m = MsgLogin{} }
func (m *MsgLogin) String() string            { return proto1.CompactTextString(m) }
func (*MsgLogin) ProtoMessage()               {}
func (*MsgLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MsgLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MsgLogin) GetMode() LoginMode {
	if m != nil {
		return m.Mode
	}
	return LoginMode_Default
}

func (m *MsgLogin) GetUserdata() []byte {
	if m != nil {
		return m.Userdata
	}
	return nil
}

func init() {
	proto1.RegisterType((*MsgLogin)(nil), "proto.MsgLogin")
	proto1.RegisterEnum("proto.MsgTypeCmd", MsgTypeCmd_name, MsgTypeCmd_value)
	proto1.RegisterEnum("proto.LoginMode", LoginMode_name, LoginMode_value)
}

func init() { proto1.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 199 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0xce, 0xc9, 0x4f, 0xcf,
	0xcc, 0xd3, 0x2b, 0x28, 0xca, 0x2f, 0xc9, 0x17, 0x62, 0x05, 0x53, 0x4a, 0x4d, 0x8c, 0x5c, 0x1c,
	0xbe, 0xc5, 0xe9, 0x3e, 0x20, 0x19, 0x21, 0x09, 0x2e, 0xf6, 0xc4, 0xe4, 0xe4, 0xfc, 0xd2, 0xbc,
	0x12, 0x09, 0x46, 0x05, 0x46, 0x0d, 0xce, 0x20, 0x18, 0x57, 0x48, 0x8a, 0x8b, 0xa3, 0x20, 0xb1,
	0xb8, 0xb8, 0x3c, 0xbf, 0x28, 0x45, 0x82, 0x09, 0x2c, 0x05, 0xe7, 0x0b, 0xa9, 0x70, 0xb1, 0xe4,
	0xe6, 0xa7, 0xa4, 0x4a, 0x30, 0x2b, 0x30, 0x6a, 0xf0, 0x19, 0x09, 0x40, 0xcc, 0xd7, 0x03, 0x9b,
	0xe8, 0x9b, 0x9f, 0x92, 0x1a, 0x04, 0x96, 0x05, 0x99, 0x50, 0x5a, 0x9c, 0x5a, 0x94, 0x92, 0x58,
	0x92, 0x28, 0xc1, 0xa2, 0xc0, 0xa8, 0xc1, 0x13, 0x04, 0xe7, 0x6b, 0x69, 0x70, 0x71, 0xf9, 0x16,
	0xa7, 0x87, 0x54, 0x16, 0xa4, 0x3a, 0xe7, 0xa6, 0x08, 0xf1, 0x73, 0x71, 0x87, 0xfa, 0x05, 0x07,
	0xb8, 0x3a, 0x7b, 0xba, 0x79, 0xba, 0xba, 0x08, 0x30, 0x08, 0x71, 0x72, 0xb1, 0x82, 0x4d, 0x13,
	0x60, 0xd4, 0x92, 0xe0, 0xe2, 0x84, 0x1b, 0x2c, 0xc4, 0xcd, 0xc5, 0xee, 0x92, 0x9a, 0x96, 0x58,
	0x9a, 0x53, 0x22, 0xc0, 0x90, 0xc4, 0x06, 0xb6, 0xd6, 0x18, 0x10, 0x00, 0x00, 0xff, 0xff, 0x6f,
	0x6a, 0x81, 0xd3, 0xe5, 0x00, 0x00, 0x00,
}
