// Code generated by protoc-gen-go. DO NOT EDIT.
// source: login.proto

/*
Package proto is a generated protocol buffer package.

It is generated from these files:
	login.proto

It has these top-level messages:
	MsgLogin
	MsgLoginResult
*/
package proto

import proto1 "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto1.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto1.ProtoPackageIsVersion2 // please upgrade the proto package

type MsgTypeCmd int32

const (
	MsgTypeCmd_UNSPECIFIED MsgTypeCmd = 0
	MsgTypeCmd_Login       MsgTypeCmd = 1
)

var MsgTypeCmd_name = map[int32]string{
	0: "UNSPECIFIED",
	1: "Login",
}
var MsgTypeCmd_value = map[string]int32{
	"UNSPECIFIED": 0,
	"Login":       1,
}

func (x MsgTypeCmd) String() string {
	return proto1.EnumName(MsgTypeCmd_name, int32(x))
}
func (MsgTypeCmd) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

type LoginMode int32

const (
	LoginMode_Default      LoginMode = 0
	LoginMode_CUSTOM_BEGIN LoginMode = 100
)

var LoginMode_name = map[int32]string{
	0:   "Default",
	100: "CUSTOM_BEGIN",
}
var LoginMode_value = map[string]int32{
	"Default":      0,
	"CUSTOM_BEGIN": 100,
}

func (x LoginMode) String() string {
	return proto1.EnumName(LoginMode_name, int32(x))
}
func (LoginMode) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

type LoginError int32

const (
	LoginError_NoErr           LoginError = 0
	LoginError_ErrPassword     LoginError = 1
	LoginError_ErrAccount      LoginError = 2
	LoginError_ErrPlatformSide LoginError = 3
	LoginError_ErrMode         LoginError = 4
	LoginError_ErrDB           LoginError = 5
	LoginError_ErrGateway      LoginError = 6
)

var LoginError_name = map[int32]string{
	0: "NoErr",
	1: "ErrPassword",
	2: "ErrAccount",
	3: "ErrPlatformSide",
	4: "ErrMode",
	5: "ErrDB",
	6: "ErrGateway",
}
var LoginError_value = map[string]int32{
	"NoErr":           0,
	"ErrPassword":     1,
	"ErrAccount":      2,
	"ErrPlatformSide": 3,
	"ErrMode":         4,
	"ErrDB":           5,
	"ErrGateway":      6,
}

func (x LoginError) String() string {
	return proto1.EnumName(LoginError_name, int32(x))
}
func (LoginError) EnumDescriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

type MsgLogin struct {
	Account  string    `protobuf:"bytes,1,opt,name=Account" json:"Account,omitempty"`
	Password string    `protobuf:"bytes,2,opt,name=Password" json:"Password,omitempty"`
	Mode     LoginMode `protobuf:"varint,3,opt,name=Mode,enum=proto.LoginMode" json:"Mode,omitempty"`
	Userdata []byte    `protobuf:"bytes,4,opt,name=Userdata,proto3" json:"Userdata,omitempty"`
}

func (m *MsgLogin) Reset()                    { *m = MsgLogin{} }
func (m *MsgLogin) String() string            { return proto1.CompactTextString(m) }
func (*MsgLogin) ProtoMessage()               {}
func (*MsgLogin) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *MsgLogin) GetAccount() string {
	if m != nil {
		return m.Account
	}
	return ""
}

func (m *MsgLogin) GetPassword() string {
	if m != nil {
		return m.Password
	}
	return ""
}

func (m *MsgLogin) GetMode() LoginMode {
	if m != nil {
		return m.Mode
	}
	return LoginMode_Default
}

func (m *MsgLogin) GetUserdata() []byte {
	if m != nil {
		return m.Userdata
	}
	return nil
}

type MsgLoginResult struct {
	Err     LoginError `protobuf:"varint,1,opt,name=Err,enum=proto.LoginError" json:"Err,omitempty"`
	Token   string     `protobuf:"bytes,2,opt,name=Token" json:"Token,omitempty"`
	Address string     `protobuf:"bytes,3,opt,name=Address" json:"Address,omitempty"`
}

func (m *MsgLoginResult) Reset()                    { *m = MsgLoginResult{} }
func (m *MsgLoginResult) String() string            { return proto1.CompactTextString(m) }
func (*MsgLoginResult) ProtoMessage()               {}
func (*MsgLoginResult) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *MsgLoginResult) GetErr() LoginError {
	if m != nil {
		return m.Err
	}
	return LoginError_NoErr
}

func (m *MsgLoginResult) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

func (m *MsgLoginResult) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func init() {
	proto1.RegisterType((*MsgLogin)(nil), "proto.MsgLogin")
	proto1.RegisterType((*MsgLoginResult)(nil), "proto.MsgLoginResult")
	proto1.RegisterEnum("proto.MsgTypeCmd", MsgTypeCmd_name, MsgTypeCmd_value)
	proto1.RegisterEnum("proto.LoginMode", LoginMode_name, LoginMode_value)
	proto1.RegisterEnum("proto.LoginError", LoginError_name, LoginError_value)
}

func init() { proto1.RegisterFile("login.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 332 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x4c, 0x90, 0xcd, 0x6e, 0xe2, 0x30,
	0x14, 0x85, 0x31, 0x10, 0x7e, 0x2e, 0x28, 0x78, 0x3c, 0xb3, 0x88, 0x66, 0x85, 0x68, 0x17, 0x51,
	0x16, 0x2c, 0xe8, 0x13, 0x14, 0x70, 0x11, 0x52, 0x43, 0x51, 0x80, 0x75, 0xe5, 0x62, 0x83, 0x50,
	0x03, 0x46, 0xd7, 0x8e, 0x10, 0xdb, 0x3e, 0x79, 0x65, 0xf3, 0xd3, 0xae, 0xac, 0xe3, 0x63, 0x9f,
	0xf3, 0xdd, 0x0b, 0xad, 0x5c, 0x6f, 0x77, 0x87, 0xfe, 0x11, 0xb5, 0xd5, 0x2c, 0xf0, 0x47, 0xef,
	0x8b, 0x40, 0x23, 0x35, 0xdb, 0x57, 0xe7, 0xb0, 0x08, 0xea, 0xcf, 0xeb, 0xb5, 0x2e, 0x0e, 0x36,
	0x22, 0x5d, 0x12, 0x37, 0xb3, 0x9b, 0x64, 0xff, 0xa1, 0x31, 0x17, 0xc6, 0x9c, 0x34, 0xca, 0xa8,
	0xec, 0xad, 0xbb, 0x66, 0x8f, 0x50, 0x4d, 0xb5, 0x54, 0x51, 0xa5, 0x4b, 0xe2, 0x70, 0x40, 0x2f,
	0xf9, 0x7d, 0x9f, 0xe8, 0xee, 0x33, 0xef, 0xba, 0x84, 0x95, 0x51, 0x28, 0x85, 0x15, 0x51, 0xb5,
	0x4b, 0xe2, 0x76, 0x76, 0xd7, 0x3d, 0x05, 0xe1, 0x8d, 0x21, 0x53, 0xa6, 0xc8, 0x2d, 0x7b, 0x80,
	0x0a, 0x47, 0xf4, 0x14, 0xe1, 0xe0, 0xcf, 0xef, 0x48, 0x8e, 0xa8, 0x31, 0x73, 0x2e, 0xfb, 0x07,
	0xc1, 0x52, 0x7f, 0xaa, 0xc3, 0x95, 0xe8, 0x22, 0xfc, 0x10, 0x52, 0xa2, 0x32, 0xc6, 0x13, 0xb9,
	0x21, 0x2e, 0x32, 0x89, 0x01, 0x52, 0xb3, 0x5d, 0x9e, 0x8f, 0x6a, 0xb4, 0x97, 0xac, 0x03, 0xad,
	0xd5, 0x6c, 0x31, 0xe7, 0xa3, 0xe9, 0xcb, 0x94, 0x8f, 0x69, 0x89, 0x35, 0x21, 0xf0, 0x0d, 0x94,
	0x24, 0x09, 0x34, 0xef, 0xfc, 0xac, 0x05, 0xf5, 0xb1, 0xda, 0x88, 0x22, 0xb7, 0xb4, 0xc4, 0x28,
	0xb4, 0x47, 0xab, 0xc5, 0xf2, 0x2d, 0x7d, 0x1f, 0xf2, 0xc9, 0x74, 0x46, 0x65, 0x52, 0x00, 0xfc,
	0x80, 0xb9, 0x90, 0x99, 0xe6, 0x88, 0xb4, 0xe4, 0x0a, 0x38, 0xe2, 0x6d, 0x4d, 0x94, 0xb0, 0x10,
	0x80, 0x23, 0x5e, 0x57, 0x4a, 0xcb, 0xec, 0x2f, 0x74, 0xdc, 0x83, 0x5c, 0xd8, 0x8d, 0xc6, 0xfd,
	0x62, 0x27, 0x15, 0xad, 0xb8, 0x36, 0x8e, 0xe8, 0x8a, 0x69, 0xd5, 0xa5, 0x71, 0xc4, 0xf1, 0x90,
	0x06, 0xd7, 0xcf, 0x13, 0x61, 0xd5, 0x49, 0x9c, 0x69, 0xed, 0xa3, 0xe6, 0x77, 0xf2, 0xf4, 0x1d,
	0x00, 0x00, 0xff, 0xff, 0x36, 0xa5, 0x72, 0x45, 0xd5, 0x01, 0x00, 0x00,
}
