/// -------------------------------------------------------------------------------
/// THIS FILE IS ORIGINALLY GENERATED BY redis2go.exe.
/// PLEASE DO NOT MODIFY THIS FILE.
/// -------------------------------------------------------------------------------

package db

import (
	"errors"

	go_redis_orm "github.com/fananchong/go-redis-orm.v2"
	"github.com/gomodule/redigo/redis"
)

type Token struct {
	Key   string
	token string
	uid   uint64

	__dirtyData map[string]interface{}
	__isLoad    bool
	__dbKey     string
	__dbName    string
	__expire    uint
}

func NewToken(dbName string, key string) *Token {
	return &Token{
		Key:         key,
		__dbName:    dbName,
		__dbKey:     "Token:" + key,
		__dirtyData: make(map[string]interface{}),
	}
}

// 若访问数据库失败返回-1；若 key 存在返回 1 ，否则返回 0 。
func (this *Token) HasKey() (int, error) {
	db := go_redis_orm.GetDB(this.__dbName)
	val, err := redis.Int(db.Do("EXISTS", this.__dbKey))
	if err != nil {
		return -1, err
	}
	return val, nil
}

func (this *Token) Load() error {
	if this.__isLoad == true {
		return errors.New("alreay load!")
	}
	db := go_redis_orm.GetDB(this.__dbName)
	val, err := redis.Values(db.Do("HGETALL", this.__dbKey))
	if err != nil {
		return err
	}
	if len(val) == 0 {
		return go_redis_orm.ERR_ISNOT_EXIST_KEY
	}
	var data struct {
		Token string `redis:"token"`
		Uid   uint64 `redis:"uid"`
	}
	if err := redis.ScanStruct(val, &data); err != nil {
		return err
	}
	this.token = data.Token
	this.uid = data.Uid
	this.__isLoad = true
	return nil
}

func (this *Token) Save() error {
	if len(this.__dirtyData) == 0 {
		return nil
	}
	db := go_redis_orm.GetDB(this.__dbName)
	if _, err := db.Do("HMSET", redis.Args{}.Add(this.__dbKey).AddFlat(this.__dirtyData)...); err != nil {
		return err
	}
	if this.__expire != 0 {
		if _, err := db.Do("EXPIRE", this.__dbKey, this.__expire); err != nil {
			return err
		}
	}
	this.__dirtyData = make(map[string]interface{})
	return nil
}

func (this *Token) Delete() error {
	db := go_redis_orm.GetDB(this.__dbName)
	_, err := db.Do("DEL", this.__dbKey)
	if err == nil {
		this.__isLoad = false
		this.__dirtyData = make(map[string]interface{})
	}
	return err
}

func (this *Token) IsLoad() bool {
	return this.__isLoad
}

func (this *Token) Expire(v uint) {
	this.__expire = v
}

func (this *Token) GetToken() string {
	return this.token
}

func (this *Token) GetUid() uint64 {
	return this.uid
}

func (this *Token) SetToken(value string) {
	this.token = value
	this.__dirtyData["token"] = value
}

func (this *Token) SetUid(value uint64) {
	this.uid = value
	this.__dirtyData["uid"] = value
}
