apiVersion: v1
kind: Service
metadata:
  name: lobby
  namespace: go-x
  labels:
    app: lobby
spec:
  ports:
    - port: 31000
      name: ""
  clusterIP: None
  selector:
    app: lobby

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lobby
  namespace: go-x
  labels:
    app: lobby
spec:
  serviceName: lobby
  selector:
    matchLabels:
      app: lobby
  replicas: 2
  template:
    metadata:
      labels:
        app: lobby
    spec:
      serviceAccountName: sa-go-x
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: lobby
        image: 127.0.0.1:5000/fananchong/go-x
        imagePullPolicy: Always
        command: [ "./lobby", "--common-loglevel=0" ]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace



