apiVersion: v1
kind: Service
metadata:
  name: room
  namespace: go-x
  labels:
    app: room
spec:
  ports:
    - port: 31100
      name: ""
  clusterIP: None
  selector:
    app: room

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: room
  namespace: go-x
  labels:
    app: room
spec:
  serviceName: room
  selector:
    matchLabels:
      app: room
  replicas: 2
  template:
    metadata:
      labels:
        app: room
    spec:
      serviceAccountName: sa-go-x
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
      - name: room
        image: 127.0.0.1:5000/fananchong/go-x
        imagePullPolicy: Always
        command: [ "./room", "--common-loglevel=0" ]
        env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace



