version: "3"
services:
    
  sentinel1:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP1]
      replicas: 1
      restart_policy:
        delay: 60s
    ports:
      - "46379:26379"
    volumes:
      - data1:/data
    networks:
      - net
    command: /bin/bash -c "rm -f /data/redis_sentinel.conf && touch /data/redis_sentinel.conf && redis-server /data/redis_sentinel.conf --sentinel monitor NAME IP PORT NUM --sentinel down-after-milliseconds NAME 5000 --sentinel parallel-syncs NAME 1 --sentinel failover-timeout NAME 180000 --sentinel announce-ip IP1 --sentinel announce-port 46379"

  sentinel2:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP2]
      replicas: 1
      restart_policy:
        delay: 60s
    ports:
      - "46380:26379"
    volumes:
      - data2:/data
    networks:
      - net
    command: /bin/bash -c "rm -f /data/redis_sentinel.conf && touch /data/redis_sentinel.conf && redis-server /data/redis_sentinel.conf --sentinel monitor NAME IP PORT NUM --sentinel down-after-milliseconds NAME 5000 --sentinel parallel-syncs NAME 1 --sentinel failover-timeout NAME 180000 --sentinel announce-ip IP2 --sentinel announce-port 46380"

  sentinel3:
    image: redis
    deploy:
      placement:
        constraints: [node.labels.host_ip==IP3]
      replicas: 1
      restart_policy:
        delay: 60s
    ports:
      - "46381:26379"
    volumes:
      - data3:/data
    networks:
      - net
    command: /bin/bash -c "rm -f /data/redis_sentinel.conf && touch /data/redis_sentinel.conf && redis-server /data/redis_sentinel.conf --sentinel monitor NAME IP PORT NUM --sentinel down-after-milliseconds NAME 5000 --sentinel parallel-syncs NAME 1 --sentinel failover-timeout NAME 180000 --sentinel announce-ip IP3 --sentinel announce-port 46381"
    
networks:
  net:
volumes:
  data1:
  data2:
  data3:
