
set http_proxy=127.0.0.1:1080
set https_proxy=127.0.0.1:1080

git config http.proxy http://127.0.0.1:1080
git config https.proxy https://127.0.0.1:1080

set GOPATH=%~dp0
echo %GOPATH%

go get -u -d github.com/golang/protobuf/proto/...
go get -u -d github.com/golang/glog/...
go get -u -d github.com/fananchong/gonet/...
go get -u -d github.com/fananchong/gonet_example/...
go get -u -d github.com/fananchong/go-proto-helper/...
go get -u -d github.com/FZambia/go-sentinel/...
go get -u -d github.com/go-ole/go-ole/...
go get -u -d github.com/shirou/gopsutil/...
go get -u -d github.com/fananchong/gochart/...
go get -u -d github.com/fananchong/gochart_example/...
go get -u -d github.com/koding/multiconfig/...
go get -u -d github.com/fananchong/gomap/...

go get -u -d google.golang.org/grpc/...
go get -u -d github.com/coreos/etcd/clientv3/...
go get -u -d github.com/fananchong/go-discovery/...
cd %GOPATH%/src/github.com/coreos/etcd
git checkout --no-track -B Branch_v3.2.13 v3.2.13 --

pause