
set http_proxy=127.0.0.1:1080
set https_proxy=127.0.0.1:1080

git config http.proxy http://127.0.0.1:1080
git config https.proxy https://127.0.0.1:1080

set GOPATH=%~dp0
echo %GOPATH%

go get -u -d github.com/golang/protobuf/proto/...
go get -u -d github.com/golang/glog/...
go get -u -d github.com/fananchong/gonet/...
go get -u -d github.com/fananchong/gonet_example/...
go get -u -d github.com/fananchong/go-proto-helper/...
go get -u -d github.com/FZambia/go-sentinel/...
go get -u -d github.com/go-ole/go-ole/...
go get -u -d github.com/shirou/gopsutil/...
go get -u -d github.com/fananchong/gochart/...
go get -u -d github.com/fananchong/gochart_example/...

go get -u -d google.golang.org/grpc/...
go get -u -d github.com/coreos/etcd/clientv3/...
go get -u -d github.com/fananchong/go-discovery/...
cd %GOPATH%/src/github.com/coreos/etcd
git checkout --no-track -B Branch_v3.2.10 v3.2.10 --

#go get -d github.com/googleapis/gax-go/...
#go get -d google.golang.org/api/bigquery/v2/...
#go get -d golang.org/x/debug/...
#go get -d golang.org/x/sync/semaphore/...
#go get -d github.com/google/go-cmp/cmp/...
#go get -d github.com/google/pprof/profile/...
#go get -d golang.org/x/time/rate/...
#go get -d github.com/cockroachdb/cmux/...
#go get -d github.com/coreos/go-systemd/daemon/...
#go get -d github.com/grpc-ecosystem/grpc-gateway/runtime/...
#go get -d github.com/grpc-ecosystem/go-grpc-prometheus/...
#go get -d github.com/spf13/cobra/...
#go get -d github.com/jonboulle/clockwork/...
#go get -d github.com/coreos/go-semver/semver/...
#go get -d github.com/gogo/protobuf/proto/...
#go get -d github.com/ugorji/go/codec/...
#go get -d github.com/xiang90/probing/...
#go get -d github.com/dgrijalva/jwt-go/...
#go get -d golang.org/x/crypto/bcrypt/...
#go get -d github.com/google/btree/...
#go get -d github.com/coreos/bbolt/...
#go get -d github.com/golang/groupcache/lru/...
#go get -d github.com/kr/pty/...

pause